apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"   
  name: operator
rules:
- apiGroups: ["custom.resources.com"] # "" indicates the core API group
  resources: ["deployment-objects"]
  verbs: ["get", "watch", "list"]

- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "update", "watch"]

- apiGroups: ["apps", "extensions"]
  resources: ["deployments/status"]
  verbs: ["update"]

- apiGroups: ["apps", "extensions"]
  resources: ["deployments/finalizers"]
  verbs: ["update"]

- apiGroups: ["apps", "extensions"]
  resources: ["replicasets"]
  verbs: [" create ", "delete", "get", "list", "patch", "update" , "watch"]
  
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "update" , "watch"]

- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]

  # service account
  # rolebinding
  # create manifest for clusterrolebinding
