apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
  namespace: default
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - name: operator
        image: operator:latest
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128M