apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows operator to read deployment objects and update deployments.
kind: ClusterRoleBinding
metadata:
  name: operator
subjects:
- kind: ServiceAccount
  name: operator # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: operator
  apiGroup: rbac.authorization.k8s.io