kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-reader
rules:
- apiGroups: ["custom.resources.com"] # "" indicates the core API group
  resources: ["services", "deployment-objects"]
  verbs: ["get", "watch", "list"]